vct_vpn_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: VctVpnBundle:Vctvpn:index }

vct_vpn_rtnJson:
    pattern:  /echoJson
    defaults: { _controller: VctVpnBundle:Vctvpn:echoJson }
    
vct_vpn_rtnTUser:
    pattern:  /showUser
    defaults: { _controller: VctVpnBundle:Vctvpn:showUser }
