vct_vpn_kanri_index:
    pattern:  /hello/{name}
    defaults: { _controller: VctVpnBundle:Kanri:index }

vct_vpn_kanri_info:
    pattern:  /info
    defaults: { _controller: VctVpnBundle:Kanri:info }

vct_vpn_kanri_about:
    pattern:  /about
    defaults: { _controller: VctVpnBundle:Kanri:about }

vct_vpn_kanri_new:
    pattern:  /new
    defaults: { _controller: VctVpnBundle:Kanri:new }
    
vct_vpn_kanri_delete:
    pattern:  /delete
    defaults: { _controller: VctVpnBundle:Kanri:delete }
    
vct_vpn_kanri_update:
    pattern:  /update/{user_id}
    defaults: { _controller: VctVpnBundle:Kanri:update }
    
vct_vpn_kanri_confirm:
    pattern:  /confirm/{user_id}
    defaults: { _controller: VctVpnBundle:Kanri:confirm }

vct_vpn_kanri_contact:
    pattern:  /contact
    defaults: { _controller: VctVpnBundle:Kanri:contact }