vct_vpn_kanri:
    pattern:  /hello/{name}
    defaults: { _controller: VctVpnBundle:Kanri:index }
    
vct_vpn_kanri_new:
    pattern:  /new
    defaults: { _controller: VctVpnBundle:Kanri:new }
    
vct_vpn_kanri_info:
    pattern:  /info
    defaults: { _controller: VctVpnBundle:Kanri:info }
