Vct\VpnBundle\Entity\TUser:
  properties:
    email:
      - Email: { message: email, groups: [registration]  }
      
      
Vct\VpnBundle\Entity\TPaypal:
  properties:
    userEmail:
      - Email: { message: email, groups: [registration]  }